/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.poli.view;

import br.com.poli.calculaScore.CalculaScoreComIdade;
import br.com.poli.calculaScore.CalculaScoreSemIdade;
import br.com.poli.principal.Partida;

/**
 *
 * @author dylan
 */
public class FimDeJogoFrame extends javax.swing.JFrame {

    Partida aux;

    /**
     * Creates new form FimDeJogoFrame
     */
    public FimDeJogoFrame(Partida partida) {
        this.aux = partida;
        initComponents();
        setAllTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        buttonJogarNovamente = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        textSituacao = new javax.swing.JLabel();
        grid76 = new javax.swing.JTextField();
        grid86 = new javax.swing.JTextField();
        grid66 = new javax.swing.JTextField();
        grid07 = new javax.swing.JTextField();
        grid22 = new javax.swing.JTextField();
        grid17 = new javax.swing.JTextField();
        grid32 = new javax.swing.JTextField();
        grid27 = new javax.swing.JTextField();
        grid42 = new javax.swing.JTextField();
        grid37 = new javax.swing.JTextField();
        grid52 = new javax.swing.JTextField();
        grid47 = new javax.swing.JTextField();
        grid62 = new javax.swing.JTextField();
        grid57 = new javax.swing.JTextField();
        grid72 = new javax.swing.JTextField();
        grid67 = new javax.swing.JTextField();
        grid82 = new javax.swing.JTextField();
        grid00 = new javax.swing.JTextField();
        grid03 = new javax.swing.JTextField();
        grid10 = new javax.swing.JTextField();
        grid13 = new javax.swing.JTextField();
        grid20 = new javax.swing.JTextField();
        grid23 = new javax.swing.JTextField();
        grid30 = new javax.swing.JTextField();
        grid40 = new javax.swing.JTextField();
        grid50 = new javax.swing.JTextField();
        grid60 = new javax.swing.JTextField();
        grid70 = new javax.swing.JTextField();
        grid80 = new javax.swing.JTextField();
        grid01 = new javax.swing.JTextField();
        grid77 = new javax.swing.JTextField();
        grid87 = new javax.swing.JTextField();
        grid08 = new javax.swing.JTextField();
        grid18 = new javax.swing.JTextField();
        grid33 = new javax.swing.JTextField();
        grid28 = new javax.swing.JTextField();
        grid43 = new javax.swing.JTextField();
        grid38 = new javax.swing.JTextField();
        grid53 = new javax.swing.JTextField();
        grid48 = new javax.swing.JTextField();
        grid63 = new javax.swing.JTextField();
        grid58 = new javax.swing.JTextField();
        grid73 = new javax.swing.JTextField();
        grid68 = new javax.swing.JTextField();
        grid83 = new javax.swing.JTextField();
        grid78 = new javax.swing.JTextField();
        grid04 = new javax.swing.JTextField();
        grid14 = new javax.swing.JTextField();
        grid24 = new javax.swing.JTextField();
        grid34 = new javax.swing.JTextField();
        grid88 = new javax.swing.JTextField();
        grid44 = new javax.swing.JTextField();
        grid54 = new javax.swing.JTextField();
        grid64 = new javax.swing.JTextField();
        grid74 = new javax.swing.JTextField();
        grid84 = new javax.swing.JTextField();
        grid05 = new javax.swing.JTextField();
        grid15 = new javax.swing.JTextField();
        grid25 = new javax.swing.JTextField();
        grid35 = new javax.swing.JTextField();
        grid45 = new javax.swing.JTextField();
        grid55 = new javax.swing.JTextField();
        grid65 = new javax.swing.JTextField();
        grid75 = new javax.swing.JTextField();
        grid85 = new javax.swing.JTextField();
        grid11 = new javax.swing.JTextField();
        grid06 = new javax.swing.JTextField();
        grid21 = new javax.swing.JTextField();
        grid16 = new javax.swing.JTextField();
        grid31 = new javax.swing.JTextField();
        grid26 = new javax.swing.JTextField();
        grid41 = new javax.swing.JTextField();
        grid36 = new javax.swing.JTextField();
        grid51 = new javax.swing.JTextField();
        grid46 = new javax.swing.JTextField();
        grid61 = new javax.swing.JTextField();
        grid56 = new javax.swing.JTextField();
        grid71 = new javax.swing.JTextField();
        grid81 = new javax.swing.JTextField();
        grid02 = new javax.swing.JTextField();
        grid12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel2.setText("GABARITO:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel3.setText("PONTUAÇÃO:");

        score.setFont(new java.awt.Font("DejaVu Sans Light", 2, 36)); // NOI18N
        score.setText("xxxxxxx");
        score.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                scorePropertyChange(evt);
            }
        });

        buttonJogarNovamente.setText("JOGAR NOVAMENTE");
        buttonJogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogarNovamenteActionPerformed(evt);
            }
        });

        buttonSair.setText("SAIR");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        textSituacao.setFont(new java.awt.Font("DejaVu Sans Light", 3, 36)); // NOI18N
        textSituacao.setText("VENCEU/PERDEU");
        textSituacao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textSituacaoPropertyChange(evt);
            }
        });

        grid76.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid76.setPreferredSize(new java.awt.Dimension(30, 30));

        grid86.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid86.setPreferredSize(new java.awt.Dimension(30, 30));

        grid66.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid66.setPreferredSize(new java.awt.Dimension(30, 30));

        grid07.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid07.setAlignmentX(0.0F);
        grid07.setAlignmentY(7.0F);
        grid07.setPreferredSize(new java.awt.Dimension(30, 30));

        grid22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid22.setPreferredSize(new java.awt.Dimension(30, 30));

        grid17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid17.setPreferredSize(new java.awt.Dimension(30, 30));

        grid32.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid32.setPreferredSize(new java.awt.Dimension(30, 30));

        grid27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid27.setPreferredSize(new java.awt.Dimension(30, 30));

        grid42.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid42.setPreferredSize(new java.awt.Dimension(30, 30));

        grid37.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid37.setPreferredSize(new java.awt.Dimension(30, 30));

        grid52.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid52.setPreferredSize(new java.awt.Dimension(30, 30));

        grid47.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid47.setPreferredSize(new java.awt.Dimension(30, 30));

        grid62.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid62.setPreferredSize(new java.awt.Dimension(30, 30));

        grid57.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid57.setPreferredSize(new java.awt.Dimension(30, 30));

        grid72.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid72.setPreferredSize(new java.awt.Dimension(30, 30));

        grid67.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid67.setPreferredSize(new java.awt.Dimension(30, 30));

        grid82.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid82.setPreferredSize(new java.awt.Dimension(30, 30));

        grid00.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid00.setAlignmentX(0.0F);
        grid00.setAlignmentY(0.0F);

        grid03.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid03.setAlignmentX(0.0F);
        grid03.setAlignmentY(3.0F);
        grid03.setPreferredSize(new java.awt.Dimension(30, 30));

        grid10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid10.setAlignmentX(1.0F);
        grid10.setAlignmentY(0.0F);

        grid13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid13.setPreferredSize(new java.awt.Dimension(30, 30));

        grid20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid20.setAlignmentX(2.0F);
        grid20.setAlignmentY(0.0F);
        grid20.setPreferredSize(new java.awt.Dimension(30, 30));

        grid23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid23.setPreferredSize(new java.awt.Dimension(30, 30));

        grid30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid30.setAlignmentX(3.0F);
        grid30.setAlignmentY(0.0F);
        grid30.setPreferredSize(new java.awt.Dimension(30, 30));

        grid40.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid40.setAlignmentX(4.0F);
        grid40.setAlignmentY(0.0F);
        grid40.setPreferredSize(new java.awt.Dimension(30, 30));

        grid50.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid50.setAlignmentX(5.0F);
        grid50.setAlignmentY(0.0F);
        grid50.setPreferredSize(new java.awt.Dimension(30, 30));

        grid60.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid60.setAlignmentX(6.0F);
        grid60.setAlignmentY(0.0F);
        grid60.setPreferredSize(new java.awt.Dimension(30, 30));

        grid70.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid70.setAlignmentX(7.0F);
        grid70.setAlignmentY(0.0F);
        grid70.setPreferredSize(new java.awt.Dimension(30, 30));

        grid80.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid80.setAlignmentX(8.0F);
        grid80.setAlignmentY(0.0F);
        grid80.setPreferredSize(new java.awt.Dimension(30, 30));

        grid01.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid01.setAlignmentX(0.0F);
        grid01.setAlignmentY(1.0F);
        grid01.setPreferredSize(new java.awt.Dimension(30, 30));

        grid77.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid77.setPreferredSize(new java.awt.Dimension(30, 30));

        grid87.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid87.setPreferredSize(new java.awt.Dimension(30, 30));

        grid08.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid08.setAlignmentX(0.0F);
        grid08.setAlignmentY(8.0F);
        grid08.setPreferredSize(new java.awt.Dimension(30, 30));

        grid18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid18.setPreferredSize(new java.awt.Dimension(30, 30));

        grid33.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid33.setPreferredSize(new java.awt.Dimension(30, 30));

        grid28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid28.setPreferredSize(new java.awt.Dimension(30, 30));

        grid43.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid43.setPreferredSize(new java.awt.Dimension(30, 30));

        grid38.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid38.setPreferredSize(new java.awt.Dimension(30, 30));

        grid53.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid53.setPreferredSize(new java.awt.Dimension(30, 30));

        grid48.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid48.setPreferredSize(new java.awt.Dimension(30, 30));

        grid63.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid63.setPreferredSize(new java.awt.Dimension(30, 30));

        grid58.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid58.setPreferredSize(new java.awt.Dimension(30, 30));

        grid73.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid73.setPreferredSize(new java.awt.Dimension(30, 30));

        grid68.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid68.setPreferredSize(new java.awt.Dimension(30, 30));

        grid83.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid83.setPreferredSize(new java.awt.Dimension(30, 30));

        grid78.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid78.setPreferredSize(new java.awt.Dimension(30, 30));

        grid04.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid04.setAlignmentX(0.0F);
        grid04.setAlignmentY(4.0F);
        grid04.setPreferredSize(new java.awt.Dimension(30, 30));

        grid14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid14.setPreferredSize(new java.awt.Dimension(30, 30));

        grid24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid24.setPreferredSize(new java.awt.Dimension(30, 30));

        grid34.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid34.setPreferredSize(new java.awt.Dimension(30, 30));

        grid88.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid88.setPreferredSize(new java.awt.Dimension(30, 30));

        grid44.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid44.setPreferredSize(new java.awt.Dimension(30, 30));

        grid54.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid54.setPreferredSize(new java.awt.Dimension(30, 30));

        grid64.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid64.setPreferredSize(new java.awt.Dimension(30, 30));

        grid74.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid74.setPreferredSize(new java.awt.Dimension(30, 30));

        grid84.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid84.setPreferredSize(new java.awt.Dimension(30, 30));

        grid05.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid05.setAlignmentX(0.0F);
        grid05.setAlignmentY(5.0F);
        grid05.setPreferredSize(new java.awt.Dimension(30, 30));

        grid15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid15.setPreferredSize(new java.awt.Dimension(30, 30));

        grid25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid25.setPreferredSize(new java.awt.Dimension(30, 30));

        grid35.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid35.setPreferredSize(new java.awt.Dimension(30, 30));

        grid45.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid45.setPreferredSize(new java.awt.Dimension(30, 30));

        grid55.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid55.setPreferredSize(new java.awt.Dimension(30, 30));

        grid65.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid65.setPreferredSize(new java.awt.Dimension(30, 30));

        grid75.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid75.setPreferredSize(new java.awt.Dimension(30, 30));

        grid85.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid85.setPreferredSize(new java.awt.Dimension(30, 30));

        grid11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid11.setPreferredSize(new java.awt.Dimension(30, 30));

        grid06.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid06.setAlignmentX(0.0F);
        grid06.setAlignmentY(6.0F);
        grid06.setPreferredSize(new java.awt.Dimension(30, 30));

        grid21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid21.setPreferredSize(new java.awt.Dimension(30, 30));

        grid16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid16.setPreferredSize(new java.awt.Dimension(30, 30));

        grid31.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid31.setPreferredSize(new java.awt.Dimension(30, 30));

        grid26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid26.setPreferredSize(new java.awt.Dimension(30, 30));

        grid41.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid41.setPreferredSize(new java.awt.Dimension(30, 30));

        grid36.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid36.setPreferredSize(new java.awt.Dimension(30, 30));

        grid51.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid51.setPreferredSize(new java.awt.Dimension(30, 30));

        grid46.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid46.setPreferredSize(new java.awt.Dimension(30, 30));

        grid61.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid61.setPreferredSize(new java.awt.Dimension(30, 30));

        grid56.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid56.setPreferredSize(new java.awt.Dimension(30, 30));

        grid71.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid71.setPreferredSize(new java.awt.Dimension(30, 30));

        grid81.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid81.setPreferredSize(new java.awt.Dimension(30, 30));

        grid02.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid02.setAlignmentX(0.0F);
        grid02.setAlignmentY(2.0F);
        grid02.setPreferredSize(new java.awt.Dimension(30, 30));

        grid12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        grid12.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(buttonJogarNovamente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grid07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grid37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grid67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(grid77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grid06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grid36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(grid66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(grid86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(grid02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(grid32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(grid62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(grid72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grid01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(grid71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grid00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(grid70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(grid05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(grid35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(grid65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(grid75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grid85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grid04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(grid74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grid03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grid63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(grid73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grid83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grid08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grid38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grid68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(grid78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grid88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(score)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(textSituacao)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78)
                        .addComponent(score))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(grid06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grid16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grid26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grid36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grid46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grid56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grid76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grid86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(grid66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grid88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonJogarNovamente)
                    .addComponent(buttonSair))
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogarNovamenteActionPerformed
        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_buttonJogarNovamenteActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void scorePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_scorePropertyChange
        if (aux.getIdadeJogador() == 0) {
            CalculaScoreSemIdade calcula = new CalculaScoreSemIdade();
            calcula.calcula(aux);
            score.setText("" + aux.getScore());
            //score.setText("Sem idade");
        } else {
            CalculaScoreComIdade calcula = new CalculaScoreComIdade();
            calcula.calcula(aux);
            score.setText("" + aux.getScore());
            //score.setText("Com idade");
        }
    }//GEN-LAST:event_scorePropertyChange

    private void textSituacaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textSituacaoPropertyChange
        if (aux.getVenceu()) {
            textSituacao.setText("Venceu");
        } else {
            textSituacao.setText("Perdeu");
        }
    }//GEN-LAST:event_textSituacaoPropertyChange
    public void setAllTextField() {
        grid00.setText(String.valueOf(aux.getGridTabuleiro()[0][0]));
        if (!grid00.getText().equals("0")) {
            grid00.setEditable(false);
        } else {
            grid00.setText("");
        }
        grid01.setText(String.valueOf(aux.getGridTabuleiro()[1][0]));
        if (!grid01.getText().equals("0")) {
            grid01.setEditable(false);
        } else {
            grid01.setText("");
        }
        grid02.setText(String.valueOf(aux.getGridTabuleiro()[2][0]));
        if (!grid02.getText().equals("0")) {
            grid02.setEditable(false);
        } else {
            grid02.setText("");
        }
        grid03.setText(String.valueOf(aux.getGridTabuleiro()[3][0]));
        if (!grid03.getText().equals("0")) {
            grid03.setEditable(false);
        } else {
            grid03.setText("");
        }
        grid04.setText(String.valueOf(aux.getGridTabuleiro()[4][0]));
        if (!grid04.getText().equals("0")) {
            grid04.setEditable(false);
        } else {
            grid04.setText("");
        }
        grid05.setText(String.valueOf(aux.getGridTabuleiro()[5][0]));
        if (!grid05.getText().equals("0")) {
            grid05.setEditable(false);
        } else {
            grid05.setText("");
        }
        grid06.setText(String.valueOf(aux.getGridTabuleiro()[6][0]));
        if (!grid06.getText().equals("0")) {
            grid06.setEditable(false);
        } else {
            grid06.setText("");
        }
        grid07.setText(String.valueOf(aux.getGridTabuleiro()[7][0]));
        if (!grid07.getText().equals("0")) {
            grid07.setEditable(false);
        } else {
            grid07.setText("");
        }
        grid08.setText(String.valueOf(aux.getGridTabuleiro()[8][0]));
        if (!grid08.getText().equals("0")) {
            grid08.setEditable(false);
        } else {
            grid08.setText("");
        }
        grid10.setText(String.valueOf(aux.getGridTabuleiro()[0][1]));
        if (!grid10.getText().equals("0")) {
            grid10.setEditable(false);
        } else {
            grid10.setText("");
        }
        grid11.setText(String.valueOf(aux.getGridTabuleiro()[1][1]));
        if (!grid11.getText().equals("0")) {
            grid11.setEditable(false);
        } else {
            grid11.setText("");
        }
        grid12.setText(String.valueOf(aux.getGridTabuleiro()[2][1]));
        if (!grid12.getText().equals("0")) {
            grid12.setEditable(false);
        } else {
            grid12.setText("");
        }
        grid13.setText(String.valueOf(aux.getGridTabuleiro()[3][1]));
        if (!grid13.getText().equals("0")) {
            grid13.setEditable(false);
        } else {
            grid13.setText("");
        }
        grid14.setText(String.valueOf(aux.getGridTabuleiro()[4][1]));
        if (!grid14.getText().equals("0")) {
            grid14.setEditable(false);
        } else {
            grid14.setText("");
        }
        grid15.setText(String.valueOf(aux.getGridTabuleiro()[5][1]));
        if (!grid15.getText().equals("0")) {
            grid15.setEditable(false);
        } else {
            grid15.setText("");
        }
        grid16.setText(String.valueOf(aux.getGridTabuleiro()[6][1]));
        if (!grid16.getText().equals("0")) {
            grid16.setEditable(false);
        } else {
            grid16.setText("");
        }
        grid17.setText(String.valueOf(aux.getGridTabuleiro()[7][1]));
        if (!grid17.getText().equals("0")) {
            grid17.setEditable(false);
        } else {
            grid17.setText("");
        }
        grid18.setText(String.valueOf(aux.getGridTabuleiro()[8][1]));
        if (!grid18.getText().equals("0")) {
            grid18.setEditable(false);
        } else {
            grid18.setText("");
        }
        grid20.setText(String.valueOf(aux.getGridTabuleiro()[0][2]));
        if (!grid20.getText().equals("0")) {
            grid20.setEditable(false);
        } else {
            grid20.setText("");
        }
        grid21.setText(String.valueOf(aux.getGridTabuleiro()[1][2]));
        if (!grid21.getText().equals("0")) {
            grid21.setEditable(false);
        } else {
            grid21.setText("");
        }
        grid22.setText(String.valueOf(aux.getGridTabuleiro()[2][2]));
        if (!grid22.getText().equals("0")) {
            grid02.setEditable(false);
        } else {
            grid22.setText("");
        }
        grid23.setText(String.valueOf(aux.getGridTabuleiro()[3][2]));
        if (!grid23.getText().equals("0")) {
            grid23.setEditable(false);
        } else {
            grid23.setText("");
        }
        grid24.setText(String.valueOf(aux.getGridTabuleiro()[4][2]));
        if (!grid24.getText().equals("0")) {
            grid24.setEditable(false);
        } else {
            grid24.setText("");
        }
        grid25.setText(String.valueOf(aux.getGridTabuleiro()[5][2]));
        if (!grid25.getText().equals("0")) {
            grid25.setEditable(false);
        } else {
            grid25.setText("");
        }
        grid26.setText(String.valueOf(aux.getGridTabuleiro()[6][2]));
        if (!grid26.getText().equals("0")) {
            grid26.setEditable(false);
        } else {
            grid26.setText("");
        }
        grid27.setText(String.valueOf(aux.getGridTabuleiro()[7][2]));
        if (!grid27.getText().equals("0")) {
            grid27.setEditable(false);
        } else {
            grid27.setText("");
        }
        grid28.setText(String.valueOf(aux.getGridTabuleiro()[8][2]));
        if (!grid28.getText().equals("0")) {
            grid28.setEditable(false);
        } else {
            grid28.setText("");
        }
        grid30.setText(String.valueOf(aux.getGridTabuleiro()[0][3]));
        if (!grid30.getText().equals("0")) {
            grid30.setEditable(false);
        } else {
            grid30.setText("");
        }
        grid31.setText(String.valueOf(aux.getGridTabuleiro()[1][3]));
        if (!grid31.getText().equals("0")) {
            grid31.setEditable(false);
        } else {
            grid31.setText("");
        }
        grid32.setText(String.valueOf(aux.getGridTabuleiro()[2][3]));
        if (!grid32.getText().equals("0")) {
            grid32.setEditable(false);
        } else {
            grid32.setText("");
        }
        grid33.setText(String.valueOf(aux.getGridTabuleiro()[3][3]));
        if (!grid33.getText().equals("0")) {
            grid33.setEditable(false);
        } else {
            grid33.setText("");
        }
        grid34.setText(String.valueOf(aux.getGridTabuleiro()[4][3]));
        if (!grid34.getText().equals("0")) {
            grid34.setEditable(false);
        } else {
            grid34.setText("");
        }
        grid35.setText(String.valueOf(aux.getGridTabuleiro()[5][3]));
        if (!grid35.getText().equals("0")) {
            grid35.setEditable(false);
        } else {
            grid35.setText("");
        }
        grid36.setText(String.valueOf(aux.getGridTabuleiro()[6][3]));
        if (!grid36.getText().equals("0")) {
            grid36.setEditable(false);
        } else {
            grid36.setText("");
        }
        grid37.setText(String.valueOf(aux.getGridTabuleiro()[7][3]));
        if (!grid37.getText().equals("0")) {
            grid37.setEditable(false);
        } else {
            grid37.setText("");
        }
        grid38.setText(String.valueOf(aux.getGridTabuleiro()[8][3]));
        if (!grid38.getText().equals("0")) {
            grid38.setEditable(false);
        } else {
            grid38.setText("");
        }
        grid40.setText(String.valueOf(aux.getGridTabuleiro()[0][4]));
        if (!grid40.getText().equals("0")) {
            grid40.setEditable(false);
        } else {
            grid40.setText("");
        }
        grid41.setText(String.valueOf(aux.getGridTabuleiro()[1][4]));
        if (!grid41.getText().equals("0")) {
            grid41.setEditable(false);
        } else {
            grid41.setText("");
        }
        grid42.setText(String.valueOf(aux.getGridTabuleiro()[2][4]));
        if (!grid42.getText().equals("0")) {
            grid42.setEditable(false);
        } else {
            grid42.setText("");
        }
        grid43.setText(String.valueOf(aux.getGridTabuleiro()[3][4]));
        if (!grid43.getText().equals("0")) {
            grid43.setEditable(false);
        } else {
            grid43.setText("");
        }
        grid44.setText(String.valueOf(aux.getGridTabuleiro()[4][4]));
        if (!grid44.getText().equals("0")) {
            grid44.setEditable(false);
        } else {
            grid44.setText("");
        }
        grid45.setText(String.valueOf(aux.getGridTabuleiro()[5][4]));
        if (!grid45.getText().equals("0")) {
            grid45.setEditable(false);
        } else {
            grid45.setText("");
        }
        grid46.setText(String.valueOf(aux.getGridTabuleiro()[6][4]));
        if (!grid46.getText().equals("0")) {
            grid46.setEditable(false);
        } else {
            grid46.setText("");
        }
        grid47.setText(String.valueOf(aux.getGridTabuleiro()[7][4]));
        if (!grid47.getText().equals("0")) {
            grid47.setEditable(false);
        } else {
            grid47.setText("");
        }
        grid48.setText(String.valueOf(aux.getGridTabuleiro()[8][4]));
        if (!grid48.getText().equals("0")) {
            grid48.setEditable(false);
        } else {
            grid48.setText("");
        }
        grid50.setText(String.valueOf(aux.getGridTabuleiro()[0][5]));
        if (!grid50.getText().equals("0")) {
            grid50.setEditable(false);
        } else {
            grid50.setText("");
        }
        grid51.setText(String.valueOf(aux.getGridTabuleiro()[1][5]));
        if (!grid51.getText().equals("0")) {
            grid51.setEditable(false);
        } else {
            grid51.setText("");
        }
        grid52.setText(String.valueOf(aux.getGridTabuleiro()[2][5]));
        if (!grid52.getText().equals("0")) {
            grid52.setEditable(false);
        } else {
            grid52.setText("");
        }
        grid53.setText(String.valueOf(aux.getGridTabuleiro()[3][5]));
        if (!grid53.getText().equals("0")) {
            grid53.setEditable(false);
        } else {
            grid53.setText("");
        }
        grid54.setText(String.valueOf(aux.getGridTabuleiro()[4][5]));
        if (!grid54.getText().equals("0")) {
            grid54.setEditable(false);
        } else {
            grid54.setText("");
        }
        grid55.setText(String.valueOf(aux.getGridTabuleiro()[5][5]));
        if (!grid55.getText().equals("0")) {
            grid55.setEditable(false);
        } else {
            grid55.setText("");
        }
        grid56.setText(String.valueOf(aux.getGridTabuleiro()[6][5]));
        if (!grid56.getText().equals("0")) {
            grid56.setEditable(false);
        } else {
            grid56.setText("");
        }
        grid57.setText(String.valueOf(aux.getGridTabuleiro()[7][5]));
        if (!grid57.getText().equals("0")) {
            grid57.setEditable(false);
        } else {
            grid57.setText("");
        }
        grid58.setText(String.valueOf(aux.getGridTabuleiro()[8][5]));
        if (!grid58.getText().equals("0")) {
            grid58.setEditable(false);
        } else {
            grid58.setText("");
        }
        grid60.setText(String.valueOf(aux.getGridTabuleiro()[0][6]));
        if (!grid60.getText().equals("0")) {
            grid60.setEditable(false);
        } else {
            grid60.setText("");
        }
        grid61.setText(String.valueOf(aux.getGridTabuleiro()[1][6]));
        if (!grid61.getText().equals("0")) {
            grid61.setEditable(false);
        } else {
            grid61.setText("");
        }
        grid62.setText(String.valueOf(aux.getGridTabuleiro()[2][6]));
        if (!grid62.getText().equals("0")) {
            grid62.setEditable(false);
        } else {
            grid62.setText("");
        }
        grid63.setText(String.valueOf(aux.getGridTabuleiro()[3][6]));
        if (!grid63.getText().equals("0")) {
            grid63.setEditable(false);
        } else {
            grid63.setText("");
        }
        grid64.setText(String.valueOf(aux.getGridTabuleiro()[4][6]));
        if (!grid64.getText().equals("0")) {
            grid64.setEditable(false);
        } else {
            grid64.setText("");
        }
        grid65.setText(String.valueOf(aux.getGridTabuleiro()[5][6]));
        if (!grid65.getText().equals("0")) {
            grid65.setEditable(false);
        } else {
            grid65.setText("");
        }
        grid66.setText(String.valueOf(aux.getGridTabuleiro()[6][6]));
        if (!grid66.getText().equals("0")) {
            grid66.setEditable(false);
        } else {
            grid66.setText("");
        }
        grid67.setText(String.valueOf(aux.getGridTabuleiro()[7][6]));
        if (!grid67.getText().equals("0")) {
            grid67.setEditable(false);
        } else {
            grid67.setText("");
        }
        grid68.setText(String.valueOf(aux.getGridTabuleiro()[8][6]));
        if (!grid68.getText().equals("0")) {
            grid68.setEditable(false);
        } else {
            grid68.setText("");
        }
        grid70.setText(String.valueOf(aux.getGridTabuleiro()[0][7]));
        if (!grid70.getText().equals("0")) {
            grid70.setEditable(false);
        } else {
            grid70.setText("");
        }
        grid71.setText(String.valueOf(aux.getGridTabuleiro()[1][7]));
        if (!grid71.getText().equals("0")) {
            grid71.setEditable(false);
        } else {
            grid71.setText("");
        }
        grid72.setText(String.valueOf(aux.getGridTabuleiro()[2][7]));
        if (!grid72.getText().equals("0")) {
            grid72.setEditable(false);
        } else {
            grid72.setText("");
        }
        grid73.setText(String.valueOf(aux.getGridTabuleiro()[3][7]));
        if (!grid73.getText().equals("0")) {
            grid73.setEditable(false);
        } else {
            grid73.setText("");
        }
        grid74.setText(String.valueOf(aux.getGridTabuleiro()[4][7]));
        if (!grid74.getText().equals("0")) {
            grid74.setEditable(false);
        } else {
            grid74.setText("");
        }
        grid75.setText(String.valueOf(aux.getGridTabuleiro()[5][7]));
        if (!grid75.getText().equals("0")) {
            grid75.setEditable(false);
        } else {
            grid75.setText("");
        }
        grid76.setText(String.valueOf(aux.getGridTabuleiro()[6][7]));
        if (!grid76.getText().equals("0")) {
            grid76.setEditable(false);
        } else {
            grid76.setText("");
        }
        grid77.setText(String.valueOf(aux.getGridTabuleiro()[7][7]));
        if (!grid77.getText().equals("0")) {
            grid77.setEditable(false);
        } else {
            grid77.setText("");
        }
        grid78.setText(String.valueOf(aux.getGridTabuleiro()[8][7]));
        if (!grid78.getText().equals("0")) {
            grid78.setEditable(false);
        } else {
            grid78.setText("");
        }
        grid80.setText(String.valueOf(aux.getGridTabuleiro()[0][8]));
        if (!grid80.getText().equals("0")) {
            grid80.setEditable(false);
        } else {
            grid80.setText("");
        }
        grid81.setText(String.valueOf(aux.getGridTabuleiro()[1][8]));
        if (!grid81.getText().equals("0")) {
            grid81.setEditable(false);
        } else {
            grid81.setText("");
        }
        grid82.setText(String.valueOf(aux.getGridTabuleiro()[2][8]));
        if (!grid82.getText().equals("0")) {
            grid82.setEditable(false);
        } else {
            grid82.setText("");
        }
        grid83.setText(String.valueOf(aux.getGridTabuleiro()[3][8]));
        if (!grid83.getText().equals("0")) {
            grid83.setEditable(false);
        } else {
            grid83.setText("");
        }
        grid84.setText(String.valueOf(aux.getGridTabuleiro()[4][8]));
        if (!grid84.getText().equals("0")) {
            grid84.setEditable(false);
        } else {
            grid84.setText("");
        }
        grid85.setText(String.valueOf(aux.getGridTabuleiro()[5][8]));
        if (!grid85.getText().equals("0")) {
            grid85.setEditable(false);
        } else {
            grid85.setText("");
        }
        grid86.setText(String.valueOf(aux.getGridTabuleiro()[6][8]));
        if (!grid86.getText().equals("0")) {
            grid86.setEditable(false);
        } else {
            grid86.setText("");
        }
        grid87.setText(String.valueOf(aux.getGridTabuleiro()[7][8]));
        if (!grid87.getText().equals("0")) {
            grid87.setEditable(false);
        } else {
            grid87.setText("");
        }
        grid88.setText(String.valueOf(aux.getGridTabuleiro()[8][8]));
        if (!grid88.getText().equals("0")) {
            grid88.setEditable(false);
        } else {
            grid88.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FimDeJogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FimDeJogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FimDeJogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FimDeJogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FimDeJogoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonJogarNovamente;
    private javax.swing.JButton buttonSair;
    private javax.swing.JTextField grid00;
    private javax.swing.JTextField grid01;
    private javax.swing.JTextField grid02;
    private javax.swing.JTextField grid03;
    private javax.swing.JTextField grid04;
    private javax.swing.JTextField grid05;
    private javax.swing.JTextField grid06;
    private javax.swing.JTextField grid07;
    private javax.swing.JTextField grid08;
    private javax.swing.JTextField grid10;
    private javax.swing.JTextField grid11;
    private javax.swing.JTextField grid12;
    private javax.swing.JTextField grid13;
    private javax.swing.JTextField grid14;
    private javax.swing.JTextField grid15;
    private javax.swing.JTextField grid16;
    private javax.swing.JTextField grid17;
    private javax.swing.JTextField grid18;
    private javax.swing.JTextField grid20;
    private javax.swing.JTextField grid21;
    private javax.swing.JTextField grid22;
    private javax.swing.JTextField grid23;
    private javax.swing.JTextField grid24;
    private javax.swing.JTextField grid25;
    private javax.swing.JTextField grid26;
    private javax.swing.JTextField grid27;
    private javax.swing.JTextField grid28;
    private javax.swing.JTextField grid30;
    private javax.swing.JTextField grid31;
    private javax.swing.JTextField grid32;
    private javax.swing.JTextField grid33;
    private javax.swing.JTextField grid34;
    private javax.swing.JTextField grid35;
    private javax.swing.JTextField grid36;
    private javax.swing.JTextField grid37;
    private javax.swing.JTextField grid38;
    private javax.swing.JTextField grid40;
    private javax.swing.JTextField grid41;
    private javax.swing.JTextField grid42;
    private javax.swing.JTextField grid43;
    private javax.swing.JTextField grid44;
    private javax.swing.JTextField grid45;
    private javax.swing.JTextField grid46;
    private javax.swing.JTextField grid47;
    private javax.swing.JTextField grid48;
    private javax.swing.JTextField grid50;
    private javax.swing.JTextField grid51;
    private javax.swing.JTextField grid52;
    private javax.swing.JTextField grid53;
    private javax.swing.JTextField grid54;
    private javax.swing.JTextField grid55;
    private javax.swing.JTextField grid56;
    private javax.swing.JTextField grid57;
    private javax.swing.JTextField grid58;
    private javax.swing.JTextField grid60;
    private javax.swing.JTextField grid61;
    private javax.swing.JTextField grid62;
    private javax.swing.JTextField grid63;
    private javax.swing.JTextField grid64;
    private javax.swing.JTextField grid65;
    private javax.swing.JTextField grid66;
    private javax.swing.JTextField grid67;
    private javax.swing.JTextField grid68;
    private javax.swing.JTextField grid70;
    private javax.swing.JTextField grid71;
    private javax.swing.JTextField grid72;
    private javax.swing.JTextField grid73;
    private javax.swing.JTextField grid74;
    private javax.swing.JTextField grid75;
    private javax.swing.JTextField grid76;
    private javax.swing.JTextField grid77;
    private javax.swing.JTextField grid78;
    private javax.swing.JTextField grid80;
    private javax.swing.JTextField grid81;
    private javax.swing.JTextField grid82;
    private javax.swing.JTextField grid83;
    private javax.swing.JTextField grid84;
    private javax.swing.JTextField grid85;
    private javax.swing.JTextField grid86;
    private javax.swing.JTextField grid87;
    private javax.swing.JTextField grid88;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel score;
    private javax.swing.JLabel textSituacao;
    // End of variables declaration//GEN-END:variables
}
